-- 方案一：使用 BIGSERIAL（传统方式，最常用）
CREATE TABLE post_algorithm (
                                id BIGSERIAL PRIMARY KEY,
                                metric_key VARCHAR(50) NOT NULL,
                                metric_value DECIMAL(10,4) NOT NULL,
                                description VARCHAR(255),
                                deleted          SMALLINT     NOT NULL DEFAULT 0,   -- 逻辑删除 0=正常 1=删除
                                version          INTEGER      NOT NULL DEFAULT 0,   -- 乐观锁
                                created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                created_by       VARCHAR(64),
                                updated_by       VARCHAR(64)
);

-- 或者方案二：使用 SQL 标准语法（PostgreSQL 10+ 推荐）
CREATE TABLE post_algorithm (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                metric_key VARCHAR(50) NOT NULL,
                                metric_value DECIMAL(10,4) NOT NULL,
                                description VARCHAR(255),
                                deleted          SMALLINT     NOT NULL DEFAULT 0,   -- 逻辑删除 0=正常 1=删除
                                version          INTEGER      NOT NULL DEFAULT 0,   -- 乐观锁
                                created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                created_by       VARCHAR(64),
                                updated_by       VARCHAR(64)
);

-- 插入数据（两种方案通用）
INSERT INTO post_algorithm (metric_key, metric_value, description) VALUES
                                                                       ('view', 0.1, '浏览权重，防刷'),
                                                                       ('like', 3.0, '点赞权重'),
                                                                       ('comment', 10.0, '评论权重'),
                                                                       ('collect', 15.0, '收藏权重'),
                                                                       ('share', 12.0, '分享权重'),
                                                                       ('manual', 10.0, '人工干预权重'),
                                                                       ('decay_lambda', 0.08, '时间衰减系数，约8小时半衰期');
